FROM docker-ppbd-prod.sfera-t1.ru/appsec-docker-private/node:20-alpine AS builder
WORKDIR /app
COPY web/react/package*.json ./
RUN npm config set registry https://proxy-ppbd-prod.sfera-t1.ru/repository/APPSEC-npm-proxy-group/
RUN npm install
COPY web/react/ ./
RUN npm run build

FROM docker-ppbd-prod.sfera-t1.ru/appsec-docker-private/nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY web/react/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
